Repository ember-cli/ember-page-title, pull requests merged in 2023-10, with the labels that each got.

#265 Add the last v4 to ember-try
  .github/workflows/ci.yml
  test-app/config/ember-try.js
Labels: Compatability, internal

#268 Switch to pnpm. yarn@v1 can't be trusted
  .github/workflows/ci.yml
  CONTRIBUTING.md
  RELEASE.md
  docs/config/ember-cli-update.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-app/config/ember-cli-update.json
  test-app/config/ember-try.js
  test-app/package.json
  yarn.lock
Labels: internal

#262 Re-export `pageTitle` from index
  addon/README.md
  addon/rollup.config.js
  addon/src/index.js
Labels: documentation, enhancement

#271 Update the lockfile
  pnpm-lock.yaml
Labels: internal
