Repository ember-cli/ember-page-title, pull requests merged in 2023-08, with the labels that each got.

#259 Fix release, beta and canary scenarios
  docs/app/helpers/highlight.js
  docs/package.json
  package.json
  test-app/package.json
  yarn.lock
Labels: Breaking

#260 Fix test command for `docs` job
  .github/workflows/ci.yml
Labels: Cleanup

#261 Add a setup for releasing via tags
  .github/workflows/ci.yml
  .github/workflows/publish-to-branch.yml
  .github/workflows/publish.yml
  RELEASE.md
  addon/package.json
  docs/package.json
  package.json
  test-app/package.json
  yarn.lock
Labels: breaking, internal, documentation
